//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarmaSMSCore
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnIncomingFormat", Namespace="http://www.karmasms.ir/")]
    public partial class ReturnIncomingFormat : object
    {
        
        private string SenderNumberField;
        
        private string RecipientNumberField;
        
        private string BodyField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SenderNumber
        {
            get
            {
                return this.SenderNumberField;
            }
            set
            {
                this.SenderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RecipientNumber
        {
            get
            {
                return this.RecipientNumberField;
            }
            set
            {
                this.RecipientNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.karmasms.ir/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="http://www.karmasms.ir/", ItemName="long")]
    public class ArrayOfLong : System.Collections.Generic.List<long>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://www.karmasms.ir/", ItemName="int")]
    public class ArrayOfInt : System.Collections.Generic.List<int>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.karmasms.ir/", ConfigurationName="KarmaSMSCore.SOAPKarmaSMSSoap")]
    public interface SOAPKarmaSMSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.karmasms.ir/GetSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<KarmaSMSCore.GetSMSResponse> GetSMSAsync(KarmaSMSCore.GetSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.karmasms.ir/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<KarmaSMSCore.SendSMSResponse> SendSMSAsync(KarmaSMSCore.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.karmasms.ir/SendSMSH", ReplyAction="*")]
        System.Threading.Tasks.Task<KarmaSMSCore.SendSMSHResponse> SendSMSHAsync(KarmaSMSCore.SendSMSHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.karmasms.ir/GetCredit", ReplyAction="*")]
        System.Threading.Tasks.Task<KarmaSMSCore.GetCreditResponse> GetCreditAsync(KarmaSMSCore.GetCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.karmasms.ir/GetRealMessageStatuses", ReplyAction="*")]
        System.Threading.Tasks.Task<KarmaSMSCore.GetRealMessageStatusesResponse> GetRealMessageStatusesAsync(KarmaSMSCore.GetRealMessageStatusesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.karmasms.ir/SendSMSEventReminder", ReplyAction="*")]
        System.Threading.Tasks.Task<KarmaSMSCore.SendSMSEventReminderResponse> SendSMSEventReminderAsync(KarmaSMSCore.SendSMSEventReminderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSMS", Namespace="http://www.karmasms.ir/", Order=0)]
        public KarmaSMSCore.GetSMSRequestBody Body;
        
        public GetSMSRequest()
        {
        }
        
        public GetSMSRequest(KarmaSMSCore.GetSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.karmasms.ir/")]
    public partial class GetSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int countMessages;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string recipientNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        public GetSMSRequestBody()
        {
        }
        
        public GetSMSRequestBody(int countMessages, string recipientNumber, string username, string password)
        {
            this.countMessages = countMessages;
            this.recipientNumber = recipientNumber;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSMSResponse", Namespace="http://www.karmasms.ir/", Order=0)]
        public KarmaSMSCore.GetSMSResponseBody Body;
        
        public GetSMSResponse()
        {
        }
        
        public GetSMSResponse(KarmaSMSCore.GetSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.karmasms.ir/")]
    public partial class GetSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KarmaSMSCore.ReturnIncomingFormat[] GetSMSResult;
        
        public GetSMSResponseBody()
        {
        }
        
        public GetSMSResponseBody(KarmaSMSCore.ReturnIncomingFormat[] GetSMSResult)
        {
            this.GetSMSResult = GetSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://www.karmasms.ir/", Order=0)]
        public KarmaSMSCore.SendSMSRequestBody Body;
        
        public SendSMSRequest()
        {
        }
        
        public SendSMSRequest(KarmaSMSCore.SendSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.karmasms.ir/")]
    public partial class SendSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KarmaSMSCore.ArrayOfString numbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string senderNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int smsClass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string password;
        
        public SendSMSRequestBody()
        {
        }
        
        public SendSMSRequestBody(KarmaSMSCore.ArrayOfString numbers, string text, string senderNumber, int smsClass, string username, string password)
        {
            this.numbers = numbers;
            this.text = text;
            this.senderNumber = senderNumber;
            this.smsClass = smsClass;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://www.karmasms.ir/", Order=0)]
        public KarmaSMSCore.SendSMSResponseBody Body;
        
        public SendSMSResponse()
        {
        }
        
        public SendSMSResponse(KarmaSMSCore.SendSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.karmasms.ir/")]
    public partial class SendSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KarmaSMSCore.ArrayOfLong SendSMSResult;
        
        public SendSMSResponseBody()
        {
        }
        
        public SendSMSResponseBody(KarmaSMSCore.ArrayOfLong SendSMSResult)
        {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSHRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSH", Namespace="http://www.karmasms.ir/", Order=0)]
        public KarmaSMSCore.SendSMSHRequestBody Body;
        
        public SendSMSHRequest()
        {
        }
        
        public SendSMSHRequest(KarmaSMSCore.SendSMSHRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.karmasms.ir/")]
    public partial class SendSMSHRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KarmaSMSCore.ArrayOfString numbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public KarmaSMSCore.ArrayOfString text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string senderNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int smsClass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string password;
        
        public SendSMSHRequestBody()
        {
        }
        
        public SendSMSHRequestBody(KarmaSMSCore.ArrayOfString numbers, KarmaSMSCore.ArrayOfString text, string senderNumber, int smsClass, string username, string password)
        {
            this.numbers = numbers;
            this.text = text;
            this.senderNumber = senderNumber;
            this.smsClass = smsClass;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSHResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSHResponse", Namespace="http://www.karmasms.ir/", Order=0)]
        public KarmaSMSCore.SendSMSHResponseBody Body;
        
        public SendSMSHResponse()
        {
        }
        
        public SendSMSHResponse(KarmaSMSCore.SendSMSHResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.karmasms.ir/")]
    public partial class SendSMSHResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KarmaSMSCore.ArrayOfLong SendSMSHResult;
        
        public SendSMSHResponseBody()
        {
        }
        
        public SendSMSHResponseBody(KarmaSMSCore.ArrayOfLong SendSMSHResult)
        {
            this.SendSMSHResult = SendSMSHResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCredit", Namespace="http://www.karmasms.ir/", Order=0)]
        public KarmaSMSCore.GetCreditRequestBody Body;
        
        public GetCreditRequest()
        {
        }
        
        public GetCreditRequest(KarmaSMSCore.GetCreditRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.karmasms.ir/")]
    public partial class GetCreditRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetCreditRequestBody()
        {
        }
        
        public GetCreditRequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCreditResponse", Namespace="http://www.karmasms.ir/", Order=0)]
        public KarmaSMSCore.GetCreditResponseBody Body;
        
        public GetCreditResponse()
        {
        }
        
        public GetCreditResponse(KarmaSMSCore.GetCreditResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.karmasms.ir/")]
    public partial class GetCreditResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double GetCreditResult;
        
        public GetCreditResponseBody()
        {
        }
        
        public GetCreditResponseBody(double GetCreditResult)
        {
            this.GetCreditResult = GetCreditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRealMessageStatusesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRealMessageStatuses", Namespace="http://www.karmasms.ir/", Order=0)]
        public KarmaSMSCore.GetRealMessageStatusesRequestBody Body;
        
        public GetRealMessageStatusesRequest()
        {
        }
        
        public GetRealMessageStatusesRequest(KarmaSMSCore.GetRealMessageStatusesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.karmasms.ir/")]
    public partial class GetRealMessageStatusesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KarmaSMSCore.ArrayOfLong messageId;
        
        public GetRealMessageStatusesRequestBody()
        {
        }
        
        public GetRealMessageStatusesRequestBody(KarmaSMSCore.ArrayOfLong messageId)
        {
            this.messageId = messageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRealMessageStatusesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRealMessageStatusesResponse", Namespace="http://www.karmasms.ir/", Order=0)]
        public KarmaSMSCore.GetRealMessageStatusesResponseBody Body;
        
        public GetRealMessageStatusesResponse()
        {
        }
        
        public GetRealMessageStatusesResponse(KarmaSMSCore.GetRealMessageStatusesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.karmasms.ir/")]
    public partial class GetRealMessageStatusesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KarmaSMSCore.ArrayOfInt GetRealMessageStatusesResult;
        
        public GetRealMessageStatusesResponseBody()
        {
        }
        
        public GetRealMessageStatusesResponseBody(KarmaSMSCore.ArrayOfInt GetRealMessageStatusesResult)
        {
            this.GetRealMessageStatusesResult = GetRealMessageStatusesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSEventReminderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSEventReminder", Namespace="http://www.karmasms.ir/", Order=0)]
        public KarmaSMSCore.SendSMSEventReminderRequestBody Body;
        
        public SendSMSEventReminderRequest()
        {
        }
        
        public SendSMSEventReminderRequest(KarmaSMSCore.SendSMSEventReminderRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.karmasms.ir/")]
    public partial class SendSMSEventReminderRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string senderNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public KarmaSMSCore.ArrayOfString numbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int hour;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int minute;
        
        public SendSMSEventReminderRequestBody()
        {
        }
        
        public SendSMSEventReminderRequestBody(string username, string password, string senderNumber, KarmaSMSCore.ArrayOfString numbers, string message, string date, int hour, int minute)
        {
            this.username = username;
            this.password = password;
            this.senderNumber = senderNumber;
            this.numbers = numbers;
            this.message = message;
            this.date = date;
            this.hour = hour;
            this.minute = minute;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSEventReminderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSEventReminderResponse", Namespace="http://www.karmasms.ir/", Order=0)]
        public KarmaSMSCore.SendSMSEventReminderResponseBody Body;
        
        public SendSMSEventReminderResponse()
        {
        }
        
        public SendSMSEventReminderResponse(KarmaSMSCore.SendSMSEventReminderResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.karmasms.ir/")]
    public partial class SendSMSEventReminderResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendSMSEventReminderResult;
        
        public SendSMSEventReminderResponseBody()
        {
        }
        
        public SendSMSEventReminderResponseBody(bool SendSMSEventReminderResult)
        {
            this.SendSMSEventReminderResult = SendSMSEventReminderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public interface SOAPKarmaSMSSoapChannel : KarmaSMSCore.SOAPKarmaSMSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public partial class SOAPKarmaSMSSoapClient : System.ServiceModel.ClientBase<KarmaSMSCore.SOAPKarmaSMSSoap>, KarmaSMSCore.SOAPKarmaSMSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SOAPKarmaSMSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SOAPKarmaSMSSoapClient.GetBindingForEndpoint(endpointConfiguration), SOAPKarmaSMSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SOAPKarmaSMSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SOAPKarmaSMSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SOAPKarmaSMSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SOAPKarmaSMSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SOAPKarmaSMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KarmaSMSCore.GetSMSResponse> KarmaSMSCore.SOAPKarmaSMSSoap.GetSMSAsync(KarmaSMSCore.GetSMSRequest request)
        {
            return base.Channel.GetSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<KarmaSMSCore.GetSMSResponse> GetSMSAsync(int countMessages, string recipientNumber, string username, string password)
        {
            KarmaSMSCore.GetSMSRequest inValue = new KarmaSMSCore.GetSMSRequest();
            inValue.Body = new KarmaSMSCore.GetSMSRequestBody();
            inValue.Body.countMessages = countMessages;
            inValue.Body.recipientNumber = recipientNumber;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((KarmaSMSCore.SOAPKarmaSMSSoap)(this)).GetSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KarmaSMSCore.SendSMSResponse> KarmaSMSCore.SOAPKarmaSMSSoap.SendSMSAsync(KarmaSMSCore.SendSMSRequest request)
        {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<KarmaSMSCore.SendSMSResponse> SendSMSAsync(KarmaSMSCore.ArrayOfString numbers, string text, string senderNumber, int smsClass, string username, string password)
        {
            KarmaSMSCore.SendSMSRequest inValue = new KarmaSMSCore.SendSMSRequest();
            inValue.Body = new KarmaSMSCore.SendSMSRequestBody();
            inValue.Body.numbers = numbers;
            inValue.Body.text = text;
            inValue.Body.senderNumber = senderNumber;
            inValue.Body.smsClass = smsClass;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((KarmaSMSCore.SOAPKarmaSMSSoap)(this)).SendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KarmaSMSCore.SendSMSHResponse> KarmaSMSCore.SOAPKarmaSMSSoap.SendSMSHAsync(KarmaSMSCore.SendSMSHRequest request)
        {
            return base.Channel.SendSMSHAsync(request);
        }
        
        public System.Threading.Tasks.Task<KarmaSMSCore.SendSMSHResponse> SendSMSHAsync(KarmaSMSCore.ArrayOfString numbers, KarmaSMSCore.ArrayOfString text, string senderNumber, int smsClass, string username, string password)
        {
            KarmaSMSCore.SendSMSHRequest inValue = new KarmaSMSCore.SendSMSHRequest();
            inValue.Body = new KarmaSMSCore.SendSMSHRequestBody();
            inValue.Body.numbers = numbers;
            inValue.Body.text = text;
            inValue.Body.senderNumber = senderNumber;
            inValue.Body.smsClass = smsClass;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((KarmaSMSCore.SOAPKarmaSMSSoap)(this)).SendSMSHAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KarmaSMSCore.GetCreditResponse> KarmaSMSCore.SOAPKarmaSMSSoap.GetCreditAsync(KarmaSMSCore.GetCreditRequest request)
        {
            return base.Channel.GetCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<KarmaSMSCore.GetCreditResponse> GetCreditAsync(string username, string password)
        {
            KarmaSMSCore.GetCreditRequest inValue = new KarmaSMSCore.GetCreditRequest();
            inValue.Body = new KarmaSMSCore.GetCreditRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((KarmaSMSCore.SOAPKarmaSMSSoap)(this)).GetCreditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KarmaSMSCore.GetRealMessageStatusesResponse> KarmaSMSCore.SOAPKarmaSMSSoap.GetRealMessageStatusesAsync(KarmaSMSCore.GetRealMessageStatusesRequest request)
        {
            return base.Channel.GetRealMessageStatusesAsync(request);
        }
        
        public System.Threading.Tasks.Task<KarmaSMSCore.GetRealMessageStatusesResponse> GetRealMessageStatusesAsync(KarmaSMSCore.ArrayOfLong messageId)
        {
            KarmaSMSCore.GetRealMessageStatusesRequest inValue = new KarmaSMSCore.GetRealMessageStatusesRequest();
            inValue.Body = new KarmaSMSCore.GetRealMessageStatusesRequestBody();
            inValue.Body.messageId = messageId;
            return ((KarmaSMSCore.SOAPKarmaSMSSoap)(this)).GetRealMessageStatusesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KarmaSMSCore.SendSMSEventReminderResponse> KarmaSMSCore.SOAPKarmaSMSSoap.SendSMSEventReminderAsync(KarmaSMSCore.SendSMSEventReminderRequest request)
        {
            return base.Channel.SendSMSEventReminderAsync(request);
        }
        
        public System.Threading.Tasks.Task<KarmaSMSCore.SendSMSEventReminderResponse> SendSMSEventReminderAsync(string username, string password, string senderNumber, KarmaSMSCore.ArrayOfString numbers, string message, string date, int hour, int minute)
        {
            KarmaSMSCore.SendSMSEventReminderRequest inValue = new KarmaSMSCore.SendSMSEventReminderRequest();
            inValue.Body = new KarmaSMSCore.SendSMSEventReminderRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.senderNumber = senderNumber;
            inValue.Body.numbers = numbers;
            inValue.Body.message = message;
            inValue.Body.date = date;
            inValue.Body.hour = hour;
            inValue.Body.minute = minute;
            return ((KarmaSMSCore.SOAPKarmaSMSSoap)(this)).SendSMSEventReminderAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SOAPKarmaSMSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SOAPKarmaSMSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SOAPKarmaSMSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://karmasms.ir/service/SOAPKarmaSMS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SOAPKarmaSMSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://karmasms.ir/service/SOAPKarmaSMS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SOAPKarmaSMSSoap,
            
            SOAPKarmaSMSSoap12,
        }
    }
}
