//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.karmasms.ir/", ConfigurationName="SOAPKarmaSMSSoap")]
public interface SOAPKarmaSMSSoap {
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.karmasms.ir/GetSMS")]
    www.karmasms.ir.ReturnIncomingFormat[] GetSMS(int countMessages, string recipientNumber, string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.karmasms.ir/SendSMS")]
    www.karmasms.ir.ArrayOfLong SendSMS(www.karmasms.ir.ArrayOfString numbers, string text, string senderNumber, int smsClass, string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.karmasms.ir/SendSMSH")]
    www.karmasms.ir.ArrayOfLong SendSMSH(www.karmasms.ir.ArrayOfString numbers, www.karmasms.ir.ArrayOfString text, string senderNumber, int smsClass, string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.karmasms.ir/GetCredit")]
    double GetCredit(string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.karmasms.ir/GetRealMessageStatuses")]
    www.karmasms.ir.ArrayOfInt GetRealMessageStatuses(www.karmasms.ir.ArrayOfLong messageId);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.karmasms.ir/SendSMSEventReminder")]
    bool SendSMSEventReminder(string username, string password, string senderNumber, www.karmasms.ir.ArrayOfString numbers, string message, string date, int hour, int minute);
}

public interface SOAPKarmaSMSSoapChannel : SOAPKarmaSMSSoap, System.ServiceModel.IClientChannel {
}

public class SOAPKarmaSMSSoapClient : System.ServiceModel.ClientBase<SOAPKarmaSMSSoap>, SOAPKarmaSMSSoap {
    
    public SOAPKarmaSMSSoapClient() {
    }
    
    public SOAPKarmaSMSSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public SOAPKarmaSMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public SOAPKarmaSMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public SOAPKarmaSMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public www.karmasms.ir.ReturnIncomingFormat[] GetSMS(int countMessages, string recipientNumber, string username, string password) {
        return base.Channel.GetSMS(countMessages, recipientNumber, username, password);
    }
    
    public www.karmasms.ir.ArrayOfLong SendSMS(www.karmasms.ir.ArrayOfString numbers, string text, string senderNumber, int smsClass, string username, string password) {
        return base.Channel.SendSMS(numbers, text, senderNumber, smsClass, username, password);
    }
    
    public www.karmasms.ir.ArrayOfLong SendSMSH(www.karmasms.ir.ArrayOfString numbers, www.karmasms.ir.ArrayOfString text, string senderNumber, int smsClass, string username, string password) {
        return base.Channel.SendSMSH(numbers, text, senderNumber, smsClass, username, password);
    }
    
    public double GetCredit(string username, string password) {
        return base.Channel.GetCredit(username, password);
    }
    
    public www.karmasms.ir.ArrayOfInt GetRealMessageStatuses(www.karmasms.ir.ArrayOfLong messageId) {
        return base.Channel.GetRealMessageStatuses(messageId);
    }
    
    public bool SendSMSEventReminder(string username, string password, string senderNumber, www.karmasms.ir.ArrayOfString numbers, string message, string date, int hour, int minute) {
        return base.Channel.SendSMSEventReminder(username, password, senderNumber, numbers, message, date, hour, minute);
    }
}
namespace www.karmasms.ir {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSMS", Namespace="http://www.karmasms.ir/")]
    public partial class GetSMS : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int countMessagesField;
        
        private string recipientNumberField;
        
        private string usernameField;
        
        private string passwordField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int countMessages {
            get {
                return this.countMessagesField;
            }
            set {
                this.countMessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string recipientNumber {
            get {
                return this.recipientNumberField;
            }
            set {
                this.recipientNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSMSResponse", Namespace="http://www.karmasms.ir/")]
    public partial class GetSMSResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private www.karmasms.ir.ReturnIncomingFormat[] GetSMSResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public www.karmasms.ir.ReturnIncomingFormat[] GetSMSResult {
            get {
                return this.GetSMSResultField;
            }
            set {
                this.GetSMSResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnIncomingFormat", Namespace="http://www.karmasms.ir/")]
    public partial class ReturnIncomingFormat : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SenderNumberField;
        
        private string RecipientNumberField;
        
        private string BodyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SenderNumber {
            get {
                return this.SenderNumberField;
            }
            set {
                this.SenderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RecipientNumber {
            get {
                return this.RecipientNumberField;
            }
            set {
                this.RecipientNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                this.BodyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSMS", Namespace="http://www.karmasms.ir/")]
    public partial class SendSMS : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private www.karmasms.ir.ArrayOfString numbersField;
        
        private string textField;
        
        private string senderNumberField;
        
        private int smsClassField;
        
        private string usernameField;
        
        private string passwordField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public www.karmasms.ir.ArrayOfString numbers {
            get {
                return this.numbersField;
            }
            set {
                this.numbersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string senderNumber {
            get {
                return this.senderNumberField;
            }
            set {
                this.senderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int smsClass {
            get {
                return this.smsClassField;
            }
            set {
                this.smsClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.karmasms.ir/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSMSResponse", Namespace="http://www.karmasms.ir/")]
    public partial class SendSMSResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private www.karmasms.ir.ArrayOfLong SendSMSResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public www.karmasms.ir.ArrayOfLong SendSMSResult {
            get {
                return this.SendSMSResultField;
            }
            set {
                this.SendSMSResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="http://www.karmasms.ir/", ItemName="long")]
    public class ArrayOfLong : System.Collections.Generic.List<long> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSMSH", Namespace="http://www.karmasms.ir/")]
    public partial class SendSMSH : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private www.karmasms.ir.ArrayOfString numbersField;
        
        private www.karmasms.ir.ArrayOfString textField;
        
        private string senderNumberField;
        
        private int smsClassField;
        
        private string usernameField;
        
        private string passwordField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public www.karmasms.ir.ArrayOfString numbers {
            get {
                return this.numbersField;
            }
            set {
                this.numbersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public www.karmasms.ir.ArrayOfString text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string senderNumber {
            get {
                return this.senderNumberField;
            }
            set {
                this.senderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int smsClass {
            get {
                return this.smsClassField;
            }
            set {
                this.smsClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSMSHResponse", Namespace="http://www.karmasms.ir/")]
    public partial class SendSMSHResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private www.karmasms.ir.ArrayOfLong SendSMSHResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public www.karmasms.ir.ArrayOfLong SendSMSHResult {
            get {
                return this.SendSMSHResultField;
            }
            set {
                this.SendSMSHResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCredit", Namespace="http://www.karmasms.ir/")]
    public partial class GetCredit : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string usernameField;
        
        private string passwordField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCreditResponse", Namespace="http://www.karmasms.ir/")]
    public partial class GetCreditResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double GetCreditResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double GetCreditResult {
            get {
                return this.GetCreditResultField;
            }
            set {
                this.GetCreditResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRealMessageStatuses", Namespace="http://www.karmasms.ir/")]
    public partial class GetRealMessageStatuses : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private www.karmasms.ir.ArrayOfLong messageIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public www.karmasms.ir.ArrayOfLong messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRealMessageStatusesResponse", Namespace="http://www.karmasms.ir/")]
    public partial class GetRealMessageStatusesResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private www.karmasms.ir.ArrayOfInt GetRealMessageStatusesResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public www.karmasms.ir.ArrayOfInt GetRealMessageStatusesResult {
            get {
                return this.GetRealMessageStatusesResultField;
            }
            set {
                this.GetRealMessageStatusesResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://www.karmasms.ir/", ItemName="int")]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSMSEventReminder", Namespace="http://www.karmasms.ir/")]
    public partial class SendSMSEventReminder : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string senderNumberField;
        
        private www.karmasms.ir.ArrayOfString numbersField;
        
        private string messageField;
        
        private string dateField;
        
        private int hourField;
        
        private int minuteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string senderNumber {
            get {
                return this.senderNumberField;
            }
            set {
                this.senderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public www.karmasms.ir.ArrayOfString numbers {
            get {
                return this.numbersField;
            }
            set {
                this.numbersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int hour {
            get {
                return this.hourField;
            }
            set {
                this.hourField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int minute {
            get {
                return this.minuteField;
            }
            set {
                this.minuteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSMSEventReminderResponse", Namespace="http://www.karmasms.ir/")]
    public partial class SendSMSEventReminderResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SendSMSEventReminderResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool SendSMSEventReminderResult {
            get {
                return this.SendSMSEventReminderResultField;
            }
            set {
                this.SendSMSEventReminderResultField = value;
            }
        }
    }
}
